/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author rodolfo
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenu_Salir = new javax.swing.JMenuItem();
        jMenu_Mantenimiento = new javax.swing.JMenu();
        jMenu_Seguridad = new javax.swing.JMenuItem();
        jMenu_MantenimientoProductos = new javax.swing.JMenuItem();
        jMenu_MantenimientoCompra = new javax.swing.JMenuItem();
        jMenu_MantenimientoHistorico = new javax.swing.JMenuItem();
        jMenu_CarritoCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArchivo.setText("Archivo");

        jMenu_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenu_Salir.setText("Salir");
        jMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenu_Salir);

        jMenuBar1.add(jMenuArchivo);

        jMenu_Mantenimiento.setText("Mantenimiento");

        jMenu_Seguridad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenu_Seguridad.setText("Modulo Seguridad");
        jMenu_Seguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SeguridadActionPerformed(evt);
            }
        });
        jMenu_Mantenimiento.add(jMenu_Seguridad);

        jMenu_MantenimientoProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenu_MantenimientoProductos.setText("Mantenimiento de Productos");
        jMenu_MantenimientoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MantenimientoProductosActionPerformed(evt);
            }
        });
        jMenu_Mantenimiento.add(jMenu_MantenimientoProductos);

        jMenu_MantenimientoCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenu_MantenimientoCompra.setText("Comprar");
        jMenu_MantenimientoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MantenimientoCompraActionPerformed(evt);
            }
        });
        jMenu_Mantenimiento.add(jMenu_MantenimientoCompra);

        jMenu_MantenimientoHistorico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenu_MantenimientoHistorico.setText("Historico de Compras");
        jMenu_Mantenimiento.add(jMenu_MantenimientoHistorico);

        jMenu_CarritoCompras.setText("Carrito de Compras");
        jMenu_Mantenimiento.add(jMenu_CarritoCompras);

        jMenuBar1.add(jMenu_Mantenimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu_SalirActionPerformed

    private void jMenu_MantenimientoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MantenimientoProductosActionPerformed
        JFrameMantenimientoProducto productos = new JFrameMantenimientoProducto();
        productos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_MantenimientoProductosActionPerformed

    private void jMenu_SeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SeguridadActionPerformed
       JFrameSeguridad seguridad = new JFrameSeguridad ();
        seguridad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu_SeguridadActionPerformed

    private void jMenu_MantenimientoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MantenimientoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_MantenimientoCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenu_CarritoCompras;
    private javax.swing.JMenu jMenu_Mantenimiento;
    private javax.swing.JMenuItem jMenu_MantenimientoCompra;
    private javax.swing.JMenuItem jMenu_MantenimientoHistorico;
    private javax.swing.JMenuItem jMenu_MantenimientoProductos;
    private javax.swing.JMenuItem jMenu_Salir;
    private javax.swing.JMenuItem jMenu_Seguridad;
    // End of variables declaration//GEN-END:variables
}
